### ISSUE TITLE
Sai typo khi thực hiện test hoạt động của flask sau khi cài

### ISSUE THREAD

**Issue by congto** [hoanvu/basic_flask_tutorial#1]
Hi @hoanvu 

Chỗ này bạn bị sai typo thì phải, lệnh chạy đúng là `python server.py` chứ nhỉ? Trong guide bạn lại để là hello.py

http://prntscr.com/g6bf02

**Comment by hoanvu** [comment]
@congto ừ đúng rồi, chắc lúc đó đang hơi ngáo :) để mình chỉnh lại

**Comment by congto** [comment]
@hoanvu ok, tui đang mò mẫm học, thấy bạn viết thực tế và dễ đọc. Cám ơn đã chia sẻ nhé.
